// Environment Setup/templates/vue/src/components/Button.vue
<script setup lang="ts">
interface Props {
	variant?: 'primary' | 'secondary'
	type?: 'button' | 'submit' | 'reset'
	disabled?: boolean
}

const props = withDefaults(defineProps<Props>(), {
	variant: 'primary',
	type: 'button',
	disabled: false,
})
</script>

<template>
	<button
		:type="type"
		:disabled="disabled"
		class="btn"
		:class="{
			'btn-primary': variant === 'primary',
			'btn-secondary': variant === 'secondary',
			'opacity-50 cursor-not-allowed': disabled,
		}"
	>
		<slot></slot>
	</button>
</template>

// Environment Setup/templates/sveltekit/src/lib/components/Button.svelte
<script lang="ts">
  export let variant: 'primary' | 'secondary' = 'primary';
  export let size: 'sm' | 'md' | 'lg' = 'md';
  export let type: 'button' | 'submit' | 'reset' = 'button';
  
  const baseClasses = variant === 'primary' ? 'btn-primary' : 'btn-secondary';
  
  const sizeClasses = {
    sm: 'text-sm px-3 py-1',
    md: 'text-base px-4 py-2',
    lg: 'text-lg px-6 py-3'
  };
</script>

<button 
  {type} 
  class="{baseClasses} {sizeClasses[size]}"
  on:click
>
  <slot />
</button>
